/**
 * Chance.js 0.5.4 (Modified)
 * Copyright (C) 2013 Victor Quinn  http://chancejs.com
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

(function(){function e(a,c){a||(a={});if(!c)return a;for(var b in c)"undefined"===typeof a[b]&&(a[b]=c[b]);return a}function h(a,c){if(a)throw new RangeError(c);}var d=function(a){void 0!==a&&("function"===typeof a?this.random=a:this.seed=a);"undefined"===typeof this.random&&(this.mt=this.mersenne_twister(a),this.random=function(){return this.mt.random(this.seed)})};d.prototype.bool=function(a){a=e(a,{likelihood:50});h(0>a.likelihood||100<a.likelihood,"Chance: Likelihood accepts values from 0 to 100.");
return 100*this.random()<a.likelihood};d.prototype.character=function(a){a=e(a);var c;h(a.alpha&&a.symbols,"Chance: Cannot specify both alpha and symbols.");c="lower"===a.casing?"abcdefghijklmnopqrstuvwxyz":"upper"===a.casing?"ABCDEFGHIJKLMNOPQRSTUVWXYZ":"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";a=a.pool?a.pool:a.alpha?c:a.symbols?"!@#$%^&*()[]":c+"0123456789!@#$%^&*()[]";return a.charAt(this.natural({max:a.length-1}))};d.prototype.floating=function(a){a=e(a,{fixed:4});var c=Math.pow(10,
a.fixed);h(a.fixed&&a.precision,"Chance: Cannot specify both fixed and precision.");var b=9007199254740992/c,d=-b;h(a.min&&a.fixed&&a.min<d,"Chance: Min specified is out of range with fixed. Min should be, at least, "+d);h(a.max&&a.fixed&&a.max>b,"Chance: Max specified is out of range with fixed. Max should be, at most, "+b);a=e(a,{min:d,max:b});a=(this.integer({min:a.min*c,max:a.max*c})/c).toFixed(a.fixed);return parseFloat(a)};d.prototype.integer=function(a){var c,b;a=e(a,{min:-9007199254740992,
max:9007199254740992});b=Math.max(Math.abs(a.min),Math.abs(a.max));do c=this.natural({max:b}),c=this.bool()?c:-1*c;while(c<a.min||c>a.max);return c};d.prototype.natural=function(a){a=e(a,{min:0,max:9007199254740992});h(a.min>a.max,"Chance: Min cannot be greater than Max.");return Math.floor(this.random()*(a.max-a.min+1)+a.min)};d.prototype.normal=function(a){a=e(a,{mean:0,dev:1});var c,b,d=a.mean;a=a.dev;do b=2*this.random()-1,c=2*this.random()-1,c=b*b+c*c;while(1<=c);b*=Math.sqrt(-2*Math.log(c)/
c);return a*b+d};d.prototype.string=function(a){a=e(a);var c=a.length||this.natural({min:5,max:20}),b="";a=a.pool;for(var d=0;d<c;d++)b+=this.character({pool:a});return b};d.prototype.capitalize=function(a){return a.charAt(0).toUpperCase()+a.substr(1)};d.prototype.mixin=function(a){for(var c in a)d.prototype[c]=a[c];return this};d.prototype.pick=function(a,c){return c&&1!==c?this.shuffle(a).slice(0,c):a[this.natural({max:a.length-1})]};d.prototype.shuffle=function(a){a=a.slice(0);for(var c=[],b=0,
d=Number(a.length),f=0;f<d;f++)b=this.natural({max:a.length-1}),c[f]=a[b],a.splice(b,1);return c};d.prototype.ampm=function(){return this.bool()?"am":"pm"};d.prototype.date=function(a){var c=this.month({raw:!0});a=e(a,{year:parseInt(this.year(),10),month:c.numeric-1,day:this.natural({min:1,max:c.days}),hour:this.hour(),minute:this.minute(),second:this.second(),millisecond:this.millisecond(),american:!0,string:!1});var b=new Date(a.year,a.month,a.day,a.hour,a.minute,a.second,a.millisecond),c=a.american?
b.getMonth()+1+"/"+b.getDate()+"/"+b.getFullYear():b.getDate()+"/"+(b.getMonth()+1)+"/"+b.getFullYear();return a.string?c:b};d.prototype.hammertime=function(a){return this.date(a).getTime()};d.prototype.hour=function(a){a=e(a);return this.natural({min:1,max:a.twentyfour?24:12})};d.prototype.millisecond=function(){return this.natural({max:999})};d.prototype.minute=d.prototype.second=function(){return this.natural({max:59})};d.prototype.month=function(a){a=e(a);var c=this.pick(this.months());return a.raw?
c:c.name};d.prototype.months=function(){return[{name:"January",short_name:"Jan",numeric:"01",days:31},{name:"February",short_name:"Feb",numeric:"02",days:28},{name:"March",short_name:"Mar",numeric:"03",days:31},{name:"April",short_name:"Apr",numeric:"04",days:30},{name:"May",short_name:"May",numeric:"05",days:31},{name:"June",short_name:"Jun",numeric:"06",days:30},{name:"July",short_name:"Jul",numeric:"07",days:31},{name:"August",short_name:"Aug",numeric:"08",days:31},{name:"September",short_name:"Sep",
numeric:"09",days:30},{name:"October",short_name:"Oct",numeric:"10",days:31},{name:"November",short_name:"Nov",numeric:"11",days:30},{name:"December",short_name:"Dec",numeric:"12",days:31}]};d.prototype.second=function(){return this.natural({max:59})};d.prototype.timestamp=function(){return this.natural({min:1,max:parseInt((new Date).getTime()/1E3,10)})};d.prototype.year=function(a){a=e(a,{min:(new Date).getFullYear()});a.max="undefined"!==typeof a.max?a.max:a.min+100;return this.natural(a).toString()};
d.prototype.d4=function(){return this.natural({min:1,max:4})};d.prototype.d6=function(){return this.natural({min:1,max:6})};d.prototype.d8=function(){return this.natural({min:1,max:8})};d.prototype.d10=function(){return this.natural({min:1,max:10})};d.prototype.d12=function(){return this.natural({min:1,max:12})};d.prototype.d20=function(){return this.natural({min:1,max:20})};d.prototype.d30=function(){return this.natural({min:1,max:30})};d.prototype.d100=function(){return this.natural({min:1,max:100})};
d.prototype.rpg=function(a,c){c=e(c);if(null===a)throw Error("A type of die roll must be included");var b=a.toLowerCase().split("d"),d=[];if(2!==b.length||!parseInt(b[0],10)||!parseInt(b[1],10))throw Error("Invalid format provided. Please provide #d# where the first # is the number of dice to roll, the second # is the max of each die");for(var f=b[0];0<f;f--)d[f-1]=this.natural({min:1,max:b[1]});return"undefined"!==typeof c.sum&&c.sum?d.reduce(function(a,b){return a+b}):d};d.prototype.guid=function(a){a=
a||{version:5};return this.string({pool:"ABCDEF1234567890",length:8})+"-"+this.string({pool:"ABCDEF1234567890",length:4})+"-"+a.version+this.string({pool:"ABCDEF1234567890",length:3})+"-"+this.string({pool:"AB89",length:1})+this.string({pool:"ABCDEF1234567890",length:3})+"-"+this.string({pool:"ABCDEF1234567890",length:12})};d.prototype.hash=function(a){a=e(a,{length:40,casing:"lower"});return this.string({pool:"upper"===a.casing?"0123456789ABCDEF":"0123456789abcdef",length:a.length})};d.prototype.luhn_check=
function(a){a=a.toString();return+a.substring(a.length-1)===this.luhn_calculate(+a.substring(0,a.length-1))};d.prototype.luhn_calculate=function(a){a=a.toString().split("").reverse();for(var c=0,b=0,d=a.length;d>b;++b){var f=+a[b];0===b%2&&(f*=2,9<f&&(f-=9));c+=f}return 9*c%10};d.prototype.mersenne_twister=function(a){return new g(a)};d.prototype.VERSION="0.5.4";var g=function(a){void 0===a&&(a=(new Date).getTime());this.N=624;this.M=397;this.MATRIX_A=2567483615;this.UPPER_MASK=2147483648;this.LOWER_MASK=
2147483647;this.mt=Array(this.N);this.mti=this.N+1;this.init_genrand(a)};g.prototype.init_genrand=function(a){this.mt[0]=a>>>0;for(this.mti=1;this.mti<this.N;this.mti++)a=this.mt[this.mti-1]^this.mt[this.mti-1]>>>30,this.mt[this.mti]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*(a&65535)+this.mti,this.mt[this.mti]>>>=0};g.prototype.init_by_array=function(a,c){var b=1,d=0,f,e;this.init_genrand(19650218);for(f=this.N>c?this.N:c;f;f--)e=this.mt[b-1]^this.mt[b-1]>>>30,this.mt[b]=(this.mt[b]^(1664525*
((e&4294901760)>>>16)<<16)+1664525*(e&65535))+a[d]+d,this.mt[b]>>>=0,b++,d++,b>=this.N&&(this.mt[0]=this.mt[this.N-1],b=1),d>=c&&(d=0);for(f=this.N-1;f;f--)e=this.mt[b-1]^this.mt[b-1]>>>30,this.mt[b]=(this.mt[b]^(1566083941*((e&4294901760)>>>16)<<16)+1566083941*(e&65535))-b,this.mt[b]>>>=0,b++,b>=this.N&&(this.mt[0]=this.mt[this.N-1],b=1);this.mt[0]=2147483648};g.prototype.genrand_int32=function(){var a,c=[0,this.MATRIX_A];if(this.mti>=this.N){var b;this.mti===this.N+1&&this.init_genrand(5489);for(b=
0;b<this.N-this.M;b++)a=this.mt[b]&this.UPPER_MASK|this.mt[b+1]&this.LOWER_MASK,this.mt[b]=this.mt[b+this.M]^a>>>1^c[a&1];for(;b<this.N-1;b++)a=this.mt[b]&this.UPPER_MASK|this.mt[b+1]&this.LOWER_MASK,this.mt[b]=this.mt[b+(this.M-this.N)]^a>>>1^c[a&1];a=this.mt[this.N-1]&this.UPPER_MASK|this.mt[0]&this.LOWER_MASK;this.mt[this.N-1]=this.mt[this.M-1]^a>>>1^c[a&1];this.mti=0}a=this.mt[this.mti++];a^=a>>>11;a^=a<<7&2636928640;a^=a<<15&4022730752;return(a^a>>>18)>>>0};g.prototype.genrand_int31=function(){return this.genrand_int32()>>>
1};g.prototype.genrand_real1=function(){return this.genrand_int32()*(1/4294967295)};g.prototype.random=function(){return this.genrand_int32()*(1/4294967296)};g.prototype.genrand_real3=function(){return(this.genrand_int32()+0.5)*(1/4294967296)};g.prototype.genrand_res53=function(){var a=this.genrand_int32()>>>5,c=this.genrand_int32()>>>6;return 1.1102230246251565E-16*(67108864*a+c)};"undefined"!==typeof exports&&("undefined"!==typeof module&&module.exports&&(exports=module.exports=d),exports.Chance=
d);"function"===typeof define&&define.amd&&define("Chance",[],function(){return d});"object"===typeof window&&"object"===typeof window.document&&(window.Chance=d,window.chance=new d)})();